const ACCESSORY_KEYWORDS = [
  'teclado gamer',
  'teclado mecanico',
  'mouse gamer',
  'mouse sem fio',
  'mouse wireless',
  'headset gamer',
  'fone gamer',
  'headset sem fio',
  'fone sem fio',
  'microfone gamer',
  'microfone usb',
  'webcam',
  'webcam full hd',
  'mousepad',
  'mousepad gamer',
  'desk mat',
  'controle gamer',
  'controle xbox',
  'controle playstation',
  'volante gamer',
  'hub usb',
  'usb hub',
  'capture card',
  'placa de captura',
  'suporte para headset',
  'base carregamento',
  'carregador sem fio',
  'braco articulado',
  'braço articulado',
  'stream deck',
  'cadeira gamer',
  'cadeira ergonomica',
  'cadeira ergonômica',
  'mesa gamer',
  'ring light',
  'microfone condensador',
  'mouse bungee',
  'paracord mouse',
  'cabo usb c',
  'cabo usb',
  'kit teclado mouse'
];

const COMPONENT_KEYWORDS = [
  'monitor',
  'monitor gamer',
  'monitor 144hz',
  'monitor 165hz',
  'monitor 240hz',
  'water cooler',
  'watercooler',
  'cooler liquido',
  'cooler líquido',
  'memoria ram',
  'memória ram',
  'ram ddr4',
  'ram ddr5',
  'ddr4',
  'ddr5',
  'ssd',
  'ssd nvme',
  'ssd m.2',
  'fonte',
  'fonte atx',
  'placa mae',
  'placa mãe',
  'processador',
  'cpu cooler'
];

export const DISCOVERY_TERMS = [
  ...ACCESSORY_KEYWORDS,
  ...COMPONENT_KEYWORDS
];

export const RELEVANT_PRODUCT_HINTS = [
  ...ACCESSORY_KEYWORDS,
  ...COMPONENT_KEYWORDS,
  'gamer accessory',
  'gaming accessory',
  'peripheral',
  'peripherals',
  'monitor gaming',
  'display gaming',
  'pc gamer accessory'
];

export const EXCLUDE_KEYWORDS = [
  'usado',
  'recondicionado',
  'refurbished',
  'defeito',
  'quebrado',
  'capinha',
  'pelicula',
  'suporte celular',
  'celular',
  'smartphone',
  'tablet',
  'iphone',
  'android'
];

export const MONITORED_CATEGORIES = [
  'Gaming Keyboard',
  'Gaming Mouse',
  'Gaming Headset',
  'Mousepad',
  'Gaming Chair',
  'Controller',
  'Microphone',
  'Webcam',
  'USB Hub',
  'Capture Card',
  'Desk Mat',
  'Gaming Accessory',
  'Peripherals',
  'PC Gamer Accessory',
  'Streaming',
  'Audio',
  'Accessories',
  'Monitor',
  'RAM',
  'Memory',
  'SSD',
  'CPU Cooler',
  'Water Cooling',
  'Processor',
  'Motherboard',
  'Power Supply'
];

export const MONITORED_STORES = [
  'Mercado Livre',
  'Kalunga',
  'Amazon',
  'Kabum',
  'TerabyteShop',
  'Pichau',
  'Magazine Luiza',
  'AliExpress',
  'Shopee'
];
